/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package cdr.types;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CurrentReading extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1881458380936715587L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CurrentReading\",\"namespace\":\"cdr.types\",\"fields\":[{\"name\":\"currentReadingID\",\"type\":\"int\"},{\"name\":\"totalReading\",\"type\":\"float\"},{\"name\":\"meterID\",\"type\":\"int\"},{\"name\":\"lastUpdate\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\",\"connect.version\":1,\"connect.name\":\"org.apache.kafka.connect.data.Timestamp\"}}],\"connect.version\":1,\"connect.name\":\"cdr.types.CurrentReading\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<CurrentReading> ENCODER =
      new BinaryMessageEncoder<CurrentReading>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CurrentReading> DECODER =
      new BinaryMessageDecoder<CurrentReading>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CurrentReading> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CurrentReading> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CurrentReading> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CurrentReading>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CurrentReading to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CurrentReading from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CurrentReading instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CurrentReading fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int currentReadingID;
  private float totalReading;
  private int meterID;
  private java.time.Instant lastUpdate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CurrentReading() {}

  /**
   * All-args constructor.
   * @param currentReadingID The new value for currentReadingID
   * @param totalReading The new value for totalReading
   * @param meterID The new value for meterID
   * @param lastUpdate The new value for lastUpdate
   */
  public CurrentReading(java.lang.Integer currentReadingID, java.lang.Float totalReading, java.lang.Integer meterID, java.time.Instant lastUpdate) {
    this.currentReadingID = currentReadingID;
    this.totalReading = totalReading;
    this.meterID = meterID;
    this.lastUpdate = lastUpdate.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return currentReadingID;
    case 1: return totalReading;
    case 2: return meterID;
    case 3: return lastUpdate;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: currentReadingID = (java.lang.Integer)value$; break;
    case 1: totalReading = (java.lang.Float)value$; break;
    case 2: meterID = (java.lang.Integer)value$; break;
    case 3: lastUpdate = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'currentReadingID' field.
   * @return The value of the 'currentReadingID' field.
   */
  public int getCurrentReadingID() {
    return currentReadingID;
  }


  /**
   * Sets the value of the 'currentReadingID' field.
   * @param value the value to set.
   */
  public void setCurrentReadingID(int value) {
    this.currentReadingID = value;
  }

  /**
   * Gets the value of the 'totalReading' field.
   * @return The value of the 'totalReading' field.
   */
  public float getTotalReading() {
    return totalReading;
  }


  /**
   * Sets the value of the 'totalReading' field.
   * @param value the value to set.
   */
  public void setTotalReading(float value) {
    this.totalReading = value;
  }

  /**
   * Gets the value of the 'meterID' field.
   * @return The value of the 'meterID' field.
   */
  public int getMeterID() {
    return meterID;
  }


  /**
   * Sets the value of the 'meterID' field.
   * @param value the value to set.
   */
  public void setMeterID(int value) {
    this.meterID = value;
  }

  /**
   * Gets the value of the 'lastUpdate' field.
   * @return The value of the 'lastUpdate' field.
   */
  public java.time.Instant getLastUpdate() {
    return lastUpdate;
  }


  /**
   * Sets the value of the 'lastUpdate' field.
   * @param value the value to set.
   */
  public void setLastUpdate(java.time.Instant value) {
    this.lastUpdate = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new CurrentReading RecordBuilder.
   * @return A new CurrentReading RecordBuilder
   */
  public static cdr.types.CurrentReading.Builder newBuilder() {
    return new cdr.types.CurrentReading.Builder();
  }

  /**
   * Creates a new CurrentReading RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CurrentReading RecordBuilder
   */
  public static cdr.types.CurrentReading.Builder newBuilder(cdr.types.CurrentReading.Builder other) {
    if (other == null) {
      return new cdr.types.CurrentReading.Builder();
    } else {
      return new cdr.types.CurrentReading.Builder(other);
    }
  }

  /**
   * Creates a new CurrentReading RecordBuilder by copying an existing CurrentReading instance.
   * @param other The existing instance to copy.
   * @return A new CurrentReading RecordBuilder
   */
  public static cdr.types.CurrentReading.Builder newBuilder(cdr.types.CurrentReading other) {
    if (other == null) {
      return new cdr.types.CurrentReading.Builder();
    } else {
      return new cdr.types.CurrentReading.Builder(other);
    }
  }

  /**
   * RecordBuilder for CurrentReading instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CurrentReading>
    implements org.apache.avro.data.RecordBuilder<CurrentReading> {

    private int currentReadingID;
    private float totalReading;
    private int meterID;
    private java.time.Instant lastUpdate;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(cdr.types.CurrentReading.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.currentReadingID)) {
        this.currentReadingID = data().deepCopy(fields()[0].schema(), other.currentReadingID);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.totalReading)) {
        this.totalReading = data().deepCopy(fields()[1].schema(), other.totalReading);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.meterID)) {
        this.meterID = data().deepCopy(fields()[2].schema(), other.meterID);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.lastUpdate)) {
        this.lastUpdate = data().deepCopy(fields()[3].schema(), other.lastUpdate);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing CurrentReading instance
     * @param other The existing instance to copy.
     */
    private Builder(cdr.types.CurrentReading other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.currentReadingID)) {
        this.currentReadingID = data().deepCopy(fields()[0].schema(), other.currentReadingID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.totalReading)) {
        this.totalReading = data().deepCopy(fields()[1].schema(), other.totalReading);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.meterID)) {
        this.meterID = data().deepCopy(fields()[2].schema(), other.meterID);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.lastUpdate)) {
        this.lastUpdate = data().deepCopy(fields()[3].schema(), other.lastUpdate);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'currentReadingID' field.
      * @return The value.
      */
    public int getCurrentReadingID() {
      return currentReadingID;
    }


    /**
      * Sets the value of the 'currentReadingID' field.
      * @param value The value of 'currentReadingID'.
      * @return This builder.
      */
    public cdr.types.CurrentReading.Builder setCurrentReadingID(int value) {
      validate(fields()[0], value);
      this.currentReadingID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'currentReadingID' field has been set.
      * @return True if the 'currentReadingID' field has been set, false otherwise.
      */
    public boolean hasCurrentReadingID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'currentReadingID' field.
      * @return This builder.
      */
    public cdr.types.CurrentReading.Builder clearCurrentReadingID() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'totalReading' field.
      * @return The value.
      */
    public float getTotalReading() {
      return totalReading;
    }


    /**
      * Sets the value of the 'totalReading' field.
      * @param value The value of 'totalReading'.
      * @return This builder.
      */
    public cdr.types.CurrentReading.Builder setTotalReading(float value) {
      validate(fields()[1], value);
      this.totalReading = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'totalReading' field has been set.
      * @return True if the 'totalReading' field has been set, false otherwise.
      */
    public boolean hasTotalReading() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'totalReading' field.
      * @return This builder.
      */
    public cdr.types.CurrentReading.Builder clearTotalReading() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'meterID' field.
      * @return The value.
      */
    public int getMeterID() {
      return meterID;
    }


    /**
      * Sets the value of the 'meterID' field.
      * @param value The value of 'meterID'.
      * @return This builder.
      */
    public cdr.types.CurrentReading.Builder setMeterID(int value) {
      validate(fields()[2], value);
      this.meterID = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'meterID' field has been set.
      * @return True if the 'meterID' field has been set, false otherwise.
      */
    public boolean hasMeterID() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'meterID' field.
      * @return This builder.
      */
    public cdr.types.CurrentReading.Builder clearMeterID() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastUpdate' field.
      * @return The value.
      */
    public java.time.Instant getLastUpdate() {
      return lastUpdate;
    }


    /**
      * Sets the value of the 'lastUpdate' field.
      * @param value The value of 'lastUpdate'.
      * @return This builder.
      */
    public cdr.types.CurrentReading.Builder setLastUpdate(java.time.Instant value) {
      validate(fields()[3], value);
      this.lastUpdate = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'lastUpdate' field has been set.
      * @return True if the 'lastUpdate' field has been set, false otherwise.
      */
    public boolean hasLastUpdate() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'lastUpdate' field.
      * @return This builder.
      */
    public cdr.types.CurrentReading.Builder clearLastUpdate() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CurrentReading build() {
      try {
        CurrentReading record = new CurrentReading();
        record.currentReadingID = fieldSetFlags()[0] ? this.currentReadingID : (java.lang.Integer) defaultValue(fields()[0]);
        record.totalReading = fieldSetFlags()[1] ? this.totalReading : (java.lang.Float) defaultValue(fields()[1]);
        record.meterID = fieldSetFlags()[2] ? this.meterID : (java.lang.Integer) defaultValue(fields()[2]);
        record.lastUpdate = fieldSetFlags()[3] ? this.lastUpdate : (java.time.Instant) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CurrentReading>
    WRITER$ = (org.apache.avro.io.DatumWriter<CurrentReading>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CurrentReading>
    READER$ = (org.apache.avro.io.DatumReader<CurrentReading>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










