/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package cdr.types;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ReadingHistory extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -725149506339942196L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ReadingHistory\",\"namespace\":\"cdr.types\",\"fields\":[{\"name\":\"reading\",\"type\":\"float\"},{\"name\":\"meterID\",\"type\":\"int\"},{\"name\":\"lastUpdate\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\",\"connect.version\":1,\"connect.name\":\"org.apache.kafka.connect.data.Timestamp\"}}],\"connect.version\":1,\"connect.name\":\"cdr.types.ReadingHistory\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<ReadingHistory> ENCODER =
      new BinaryMessageEncoder<ReadingHistory>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ReadingHistory> DECODER =
      new BinaryMessageDecoder<ReadingHistory>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ReadingHistory> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ReadingHistory> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ReadingHistory> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ReadingHistory>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ReadingHistory to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ReadingHistory from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ReadingHistory instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ReadingHistory fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private float reading;
  private int meterID;
  private java.time.Instant lastUpdate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ReadingHistory() {}

  /**
   * All-args constructor.
   * @param reading The new value for reading
   * @param meterID The new value for meterID
   * @param lastUpdate The new value for lastUpdate
   */
  public ReadingHistory(java.lang.Float reading, java.lang.Integer meterID, java.time.Instant lastUpdate) {
    this.reading = reading;
    this.meterID = meterID;
    this.lastUpdate = lastUpdate.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return reading;
    case 1: return meterID;
    case 2: return lastUpdate;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: reading = (java.lang.Float)value$; break;
    case 1: meterID = (java.lang.Integer)value$; break;
    case 2: lastUpdate = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'reading' field.
   * @return The value of the 'reading' field.
   */
  public float getReading() {
    return reading;
  }


  /**
   * Sets the value of the 'reading' field.
   * @param value the value to set.
   */
  public void setReading(float value) {
    this.reading = value;
  }

  /**
   * Gets the value of the 'meterID' field.
   * @return The value of the 'meterID' field.
   */
  public int getMeterID() {
    return meterID;
  }


  /**
   * Sets the value of the 'meterID' field.
   * @param value the value to set.
   */
  public void setMeterID(int value) {
    this.meterID = value;
  }

  /**
   * Gets the value of the 'lastUpdate' field.
   * @return The value of the 'lastUpdate' field.
   */
  public java.time.Instant getLastUpdate() {
    return lastUpdate;
  }


  /**
   * Sets the value of the 'lastUpdate' field.
   * @param value the value to set.
   */
  public void setLastUpdate(java.time.Instant value) {
    this.lastUpdate = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new ReadingHistory RecordBuilder.
   * @return A new ReadingHistory RecordBuilder
   */
  public static cdr.types.ReadingHistory.Builder newBuilder() {
    return new cdr.types.ReadingHistory.Builder();
  }

  /**
   * Creates a new ReadingHistory RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ReadingHistory RecordBuilder
   */
  public static cdr.types.ReadingHistory.Builder newBuilder(cdr.types.ReadingHistory.Builder other) {
    if (other == null) {
      return new cdr.types.ReadingHistory.Builder();
    } else {
      return new cdr.types.ReadingHistory.Builder(other);
    }
  }

  /**
   * Creates a new ReadingHistory RecordBuilder by copying an existing ReadingHistory instance.
   * @param other The existing instance to copy.
   * @return A new ReadingHistory RecordBuilder
   */
  public static cdr.types.ReadingHistory.Builder newBuilder(cdr.types.ReadingHistory other) {
    if (other == null) {
      return new cdr.types.ReadingHistory.Builder();
    } else {
      return new cdr.types.ReadingHistory.Builder(other);
    }
  }

  /**
   * RecordBuilder for ReadingHistory instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ReadingHistory>
    implements org.apache.avro.data.RecordBuilder<ReadingHistory> {

    private float reading;
    private int meterID;
    private java.time.Instant lastUpdate;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(cdr.types.ReadingHistory.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.reading)) {
        this.reading = data().deepCopy(fields()[0].schema(), other.reading);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.meterID)) {
        this.meterID = data().deepCopy(fields()[1].schema(), other.meterID);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.lastUpdate)) {
        this.lastUpdate = data().deepCopy(fields()[2].schema(), other.lastUpdate);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing ReadingHistory instance
     * @param other The existing instance to copy.
     */
    private Builder(cdr.types.ReadingHistory other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.reading)) {
        this.reading = data().deepCopy(fields()[0].schema(), other.reading);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.meterID)) {
        this.meterID = data().deepCopy(fields()[1].schema(), other.meterID);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.lastUpdate)) {
        this.lastUpdate = data().deepCopy(fields()[2].schema(), other.lastUpdate);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'reading' field.
      * @return The value.
      */
    public float getReading() {
      return reading;
    }


    /**
      * Sets the value of the 'reading' field.
      * @param value The value of 'reading'.
      * @return This builder.
      */
    public cdr.types.ReadingHistory.Builder setReading(float value) {
      validate(fields()[0], value);
      this.reading = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'reading' field has been set.
      * @return True if the 'reading' field has been set, false otherwise.
      */
    public boolean hasReading() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'reading' field.
      * @return This builder.
      */
    public cdr.types.ReadingHistory.Builder clearReading() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'meterID' field.
      * @return The value.
      */
    public int getMeterID() {
      return meterID;
    }


    /**
      * Sets the value of the 'meterID' field.
      * @param value The value of 'meterID'.
      * @return This builder.
      */
    public cdr.types.ReadingHistory.Builder setMeterID(int value) {
      validate(fields()[1], value);
      this.meterID = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'meterID' field has been set.
      * @return True if the 'meterID' field has been set, false otherwise.
      */
    public boolean hasMeterID() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'meterID' field.
      * @return This builder.
      */
    public cdr.types.ReadingHistory.Builder clearMeterID() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastUpdate' field.
      * @return The value.
      */
    public java.time.Instant getLastUpdate() {
      return lastUpdate;
    }


    /**
      * Sets the value of the 'lastUpdate' field.
      * @param value The value of 'lastUpdate'.
      * @return This builder.
      */
    public cdr.types.ReadingHistory.Builder setLastUpdate(java.time.Instant value) {
      validate(fields()[2], value);
      this.lastUpdate = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'lastUpdate' field has been set.
      * @return True if the 'lastUpdate' field has been set, false otherwise.
      */
    public boolean hasLastUpdate() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'lastUpdate' field.
      * @return This builder.
      */
    public cdr.types.ReadingHistory.Builder clearLastUpdate() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ReadingHistory build() {
      try {
        ReadingHistory record = new ReadingHistory();
        record.reading = fieldSetFlags()[0] ? this.reading : (java.lang.Float) defaultValue(fields()[0]);
        record.meterID = fieldSetFlags()[1] ? this.meterID : (java.lang.Integer) defaultValue(fields()[1]);
        record.lastUpdate = fieldSetFlags()[2] ? this.lastUpdate : (java.time.Instant) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ReadingHistory>
    WRITER$ = (org.apache.avro.io.DatumWriter<ReadingHistory>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ReadingHistory>
    READER$ = (org.apache.avro.io.DatumReader<ReadingHistory>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










